theme: jekyll-theme-slate
title: Vimal Bellamkonda
description: Student of Northwestern and Kellogg with a passion for Business Intelligence and Data science, particularly as they apply to improving patient outcomes and the greater healthcare system
