theme: jekyll-theme-cayman
title: Vimal Bellamkonda
description: Student of Northwestern and Kellogg with strong background in Business Intelligence and Data science, and a passion for improving patient outcomes and healthcare overall
