theme: jekyll-theme-slate
title: Vimal Bellamkonda
description: <img src="headshot.jpg" alt="Vimal_headshot"> 
Student of Northwestern and Kellogg with strong background in Business Intelligence and Data science, and a passion for improving patient outcomes and healthcare overall
